// <auto-generated />
using CloudNine.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudNine.Core.Migrations
{
    [DbContext(typeof(CloudNineDatabaseModel))]
    [Migration("20201105022644_QuotesMigration")]
    partial class QuotesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("CloudNine.Core.Configuration.DiscordServerConfiguration", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthdayConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
