# This is a basic workflow to help you get started with Actions

name: Website Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:         
  Uplaod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stop Current Release
        uses: garygrossgarten/github-action-ssh@release
        continue-on-error: true
        with:
          command: ${{ secrets.DOCKER_WEB_STOP_CMD }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Copy Web Project
        uses: garygrossgarten/github-action-scp@release
        with:
          local: CloudNine.Web/
          remote: ${{ secrets.WEB_RELEASE_DEST }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Copy Core Project
        uses: garygrossgarten/github-action-scp@release
        with:
          local: CloudNine.Core/
          remote: ${{ secrets.WEB_CORE_RELEASE_DEST }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Make Config Folder
        run: mkdir Config
      - name: Copy .config Files
        run: cp **.config Config/
      - name: Copy Configs
        uses: garygrossgarten/github-action-scp@release
        with:
          local: Config/
          remote: ${{ secrets.WEB_CORE_RELEASE_DEST }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Build Web Docker Image
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.DOCKER_WEB_BUILD_CMD }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Start Web Release
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.DOCKER_WEB_START_CMD }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
