# This is a basic workflow to help you get started with Actions

name: Website Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install dependencies
      run: msbuild /t:restore
    - name: Build
      run: msbuild /t:build CloudNine.Web/CloudNine.Web.csproj /p:Configuration=Release /p:RestorePackages=false /p:OutputPath=artifact/build/CloudNineWeb /p:DeployOnBuild=true /p:PublishProfile=CloudNine.Web/Properties/PublishProfile/GithubRelease.pubxml
    - name: Copy Dockerfile
      run: cp CloudNine.Web/Dockerfile.Web CloudNine.Web/artifact/
    - name: Stop Current Release
      uses: garygrossgarten/github-action-ssh@release
      continue-on-error: true
      with:
        command: ${{ secrets.DOCKER_WEB_STOP_CMD }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
        privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
    - name: Copy Files over SSH
      uses: garygrossgarten/github-action-scp@release
      with:
        local: CloudNine.Web/artifact/
        remote: ${{ secrets.RELEASE_DEST }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
        privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
    - name: Start New Release
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ${{ secrets.DOCKER_WEB_START_CMD }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
        privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
